spring:
  application:
    name: DormSys
  #数据库的连接信息
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

#Mybatis 的相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰命名自动转换
    map-underscore-to-camel-case: true

#阿里云的参数配置
aliyun:
  oss:
    endpoint: ${ALIYUN_OSS_ENDPOINT}
    bucketName: ${ALIYUN_OSS_BUCKET}
    region: ${ALIYUN_OSS_REGION}

